services:
  twin-db-local:
    container_name: twin-db-local
    image: mariadb:11.0.2
    volumes:
      - twin-db-data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      PUID: 10
      PGID: 1000
      TZ: ${TZ}
    env_file:
      - .env.development.local
    networks:
      - twin-db-local-net
    ports:
      - "${DB_EXPOSED_PORT:-3307}:${DB_PORT:-3306}"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  twin-nginx-local:
    container_name: twin-nginx-local
    build:
      context: ./nginx/
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      BACKEND_HOST: ${BACKEND_HOST:-127.0.0.1}
      BACKEND_PORT: ${BACKEND_PORT:-3000}
      FRONTEND_HOST: ${FRONTEND_HOST:-127.0.0.1}
      FRONTEND_PORT: ${FRONTEND_PORT:-3001}
    env_file:
      - .env.development.local
    ports:
      - "${NGINX_PORT:-8081}:${NGINX_PORT:-8081}"
    networks:
      - twin-nginx-local-net
    volumes:
      - uploads:/usr/share/nginx/html/uploads:ro

networks:
  twin-db-local-net:
  twin-nginx-local-net:

volumes:
  twin-db-data:
  uploads:
